### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by neil1811** [jtmelton/semgrep-idea-plugin#3]
hello , Do you have a semgrep-wrapper example that can run in windows system? 
or is there a new semgrep-idea-plugin tool that don't need semgrep-wrapper？
thank you!

**Comment by jtmelton** [comment]
Hi @neil1811 I don't have an example of the windows system (I don't have a windows box to work on / test from). There's not another tool I'm aware of that doesn't need the wrapper. By design this uses the system intellij has for external tools. You _could_ build a plugin that was native, but I don't *think* you can easily call external programs from it. You would have to package the binary to semgrep witht he plugin and do a lot of work to make it workable. I thought that wasn't the best design.
